### ISSUE TITLE
Desktop version

### ISSUE THREAD

**Issue by whoizit** [0xchat-app/0xchat-core#1]
It should be easy to create a desktop version of an application using Flutter.  Is it planned?

**Comment by water783** [comment]
Yes, it's on our roadmap. But it might take some time as we are currently focusing on perfecting the basic features.

**Comment by EsmailELBoBDev2** [comment]
yes it will be awesome!

**Comment by water783** [comment]
The desktop version is now live! Check it out here:

https://github.com/0xchat-app/0xchat-app-main/releases/tag/v1.0.0-desktop-beta

> It should be easy to create a desktop version of an application using Flutter. Is it planned?
