### ISSUE TITLE
Feature Request: NIP-46 login

### ISSUE THREAD

**Issue by aChrisYouKnow** [0xchat-app/0xchat-core#10]
It would be great to use nsec.app or nsecBunker to sign in to 0xChat. I much prefer that to pasting my private key into various apps. 

Link to NIP-46:
https://github.com/nostr-protocol/nips/blob/master/46.md

Other clients that currently support NIP-46 for testing/examples: 
https://github.com/blackcoffeexbt/awesome-nip46-remote-nostr-signing-clients

Thanks for the consideration!

**Comment by water783** [comment]
I am not going to use the remote nsec solution, as we need to frequently call nsec for encryption, decryption, signature computations and so on. Each operation would require network transmission, which would be highly inefficient. If a better remote nsec solution becomes available in the future, I will consider using it.

**Comment by aChrisYouKnow** [comment]
Understandable. Looking forward to some standardized way to do key rotation at some point. Wouldn't be so bad pasting private keys all over if there was a way to move to a new one if compromised.

**Comment by water783** [comment]
Thank you for your understanding. 0xchat for Android now supports Amber login. If you are using Android, we highly recommend using Amber to log in.
