### ISSUE TITLE
Trouble with login

### ISSUE THREAD

**Issue by 3ndpoint** [0xchat-app/0xchat-core#14]
I have nostr nsec that I use with Amethyst. I'm having trouble entering it in on the 0xchat login page. After typing the nsec, enter is not available (just newline), so that I am unable to finalize what I've typed. Is there a prefix I need to enter besides the nsec itself? 

This is probably a problem with the user (me) and not with the program, but I'm stumped for now.

I'm using 0xchat 1.4.4 apk on a pixel 7.

**Comment by water783** [comment]
Have you checked if you entered the nsec incorrectly? If it's correct, the login button will appear automatically. No need to press enter.

**Comment by 3ndpoint** [comment]
I will check. Maybe I transcribed it badly. Thank you.

**Comment by 3ndpoint** [comment]
That worked. It required me to enter "nsec" before the numbers and I had transcribed it wrong. Thanks for the help.

**Comment by water783** [comment]
You're welcome
