### ISSUE TITLE
[Feature Request] Disable Haptic Feedback

### ISSUE THREAD

**Issue by crimsonleaf363** [0xchat-app/0xchat-core#2]
### **Problem**

- Haptic feedback can't be disabled in the settings.

### **Proposed Solution**

- Allow haptic feedback to be disabled as a toggle in settings.

**Comment by water783** [comment]
> ### **Problem**
> 
> 
> 
> - Haptic feedback can't be disabled in the settings.
> 
> 
> 
> ### **Proposed Solution**
> 
> 
> 
> - Allow haptic feedback to be disabled as a toggle in settings.

Thanks, will add it to our plans

**Comment by water783** [comment]
> ### **Problem**
> 
> 
> 
> - Haptic feedback can't be disabled in the settings.
> 
> 
> 
> ### **Proposed Solution**
> 
> 
> 
> - Allow haptic feedback to be disabled as a toggle in settings.

This feature is now available on v1.2.2
