### ISSUE TITLE
Own profile view: remove nonsensical options

### ISSUE THREAD

**Issue by alltheseas** [0xchat-app/0xchat-core#6]
_what happens_

When I am viewing my own profile I see various options that make sense for other profiles, but not for mine:

1) message self
2) secret chat self
3) call self
4) mute self
5) add contact self
6) block self

![image](https://github.com/0xchat-app/0xchat-core/assets/64376233/16d7fbfc-3ef1-4c65-a30b-049abaff2d74)

_suggestion_

Remove/don't show these as options for own profile.

**Comment by water783** [comment]
Great suggestion, message self is a feature, while others can be hidden

**Comment by alltheseas** [comment]
Follow on: when I click message self remove add contact, and block buttons
![image](https://github.com/0xchat-app/0xchat-core/assets/64376233/05a31d3c-0540-444e-9d91-7a60e37fe060)

**Comment by water783** [comment]
This feature is included in the v1.2.3 release
