### ISSUE TITLE
Require auth on copy nsec

### ISSUE THREAD

**Issue by alltheseas** [0xchat-app/0xchat-core#8]
_suggestion_
On copy nsec action, require auth. 

![image](https://github.com/0xchat-app/0xchat-core/assets/64376233/a21b02bf-48c5-4893-8f14-40c584eb6e70)

![image](https://github.com/0xchat-app/0xchat-core/assets/64376233/73b4e078-8220-41ea-9fba-602bfca423fa)

Related to https://github.com/0xchat-app/0xchat-core/issues/5

**Comment by water783** [comment]
fixed in the latest version
